[package]
name = "rust-tui"
version = "0.1.0"
description = "A cross-plateform wrapper for package-manager"
authors = ["Sampong-Starluck <55474542+Sampong-Starluck@users.noreply.github.com>"]
license = "MIT"
edition = "2024"

[dependencies]
color-eyre = "0.6.5"
ratatui = "0.30.2"
crossterm = { version = "0.29.0", features = ["event-stream"] }
which = "8.0.4"
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
nanoserde = "0.2.1"
libc = "1.0.0-alpha.3"

# Read the optimization guideline for more details: https://ratatui.rs/recipes/apps/release-your-app/#optimizations
[profile.release]
codegen-units = 1
lto = true
opt-level = "s"
strip = true

[target.x86_64-unknown-linux-musl]
linker = "musl-gcc"

[target.x86_64-pc-windows-gnu]
linker = "x86_64-w64-mingw32-gcc"

[target.aarch64-unknown-linux-gnu]
linker = "aarch64-linux-gnu-gcc"